services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
    command: sh -c "npx prisma migrate dev --name init && npx ts-node-dev --respawn src/index.ts"
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run dev
